/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henry marcelo
 */
public class arriendo extends javax.swing.JInternalFrame {

    /**
     * Creates new form arriendo
     */
    public arriendo() {
        initComponents();
    }
    void listaarri(){
                 DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Libro");  
        modelo.addColumn("Costo total");
        modelo.addColumn("Fecha arriendo");
        modelo.addColumn("Fecha devolucion");
        modelo.addColumn("Fecha entrega");
        modelo.addColumn("Dias retrasados");
        modelo.addColumn("Multa");
        modelo.addColumn("Costo Arriendo");
        modelo.addColumn("Cliente");
        modelo.addColumn("Trabajador");
                       
       tablaarri.setModel(modelo);
       String []datos = new String[11];
      
       try{
       Statement st=cn.createStatement();
       ResultSet rs=st.executeQuery("SELECT * FROM arriendo");
       while(rs.next()){
           datos[0]=rs.getString(1);
           datos[1]=rs.getString(2);
           datos[2]=rs.getString(3);
           datos[3]=rs.getString(4);
           datos[4]=rs.getString(5);
           datos[5]=rs.getString(6);
           datos[6]=rs.getString(7);
           datos[7]=rs.getString(8);
           datos[8]=rs.getString(9);
           datos[9]=rs.getString(10);
           datos[10]=rs.getString(11);        
           modelo.addRow(datos);
           tablaarri.setModel(modelo);
       }
       }catch(SQLException e){
           Logger.getLogger(autor.class.getName()).log(Level.SEVERE,null, e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        codarri = new javax.swing.JTextField();
        numserie = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        fecarri = new javax.swing.JTextField();
        fecdev = new javax.swing.JTextField();
        fecent = new javax.swing.JTextField();
        diar = new javax.swing.JTextField();
        multa = new javax.swing.JTextField();
        cosarri = new javax.swing.JTextField();
        rutc = new javax.swing.JTextField();
        rutt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaarri = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Arriendo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, -1, -1));

        jLabel2.setText("Libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, -1, -1));

        jLabel3.setText("Costo total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 97, -1, -1));

        jLabel4.setText("Fecha Arriendo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 135, -1, -1));

        jLabel5.setText("Fecha Devolucion Estimada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 173, -1, -1));

        jLabel6.setText("Fecha Entrega Real");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, -1));

        jLabel7.setText("Multa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 287, -1, -1));

        jLabel8.setText("Dias Retrasado");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 249, -1, -1));

        jLabel9.setText("Costo Arriendo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 325, -1, -1));

        jLabel10.setText("Cliente");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 363, -1, -1));

        jLabel11.setText("Trabajador");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 401, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 436, -1, -1));

        jButton2.setText("Eliminar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 436, -1, -1));

        jButton3.setText("Modificar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 436, -1, -1));
        getContentPane().add(codarri, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 18, 119, -1));
        getContentPane().add(numserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 56, 119, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 94, 119, -1));
        getContentPane().add(fecarri, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 132, 119, -1));
        getContentPane().add(fecdev, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 170, 119, -1));
        getContentPane().add(fecent, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 208, 119, -1));
        getContentPane().add(diar, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 246, 119, -1));
        getContentPane().add(multa, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 284, 119, -1));
        getContentPane().add(cosarri, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 322, 119, -1));
        getContentPane().add(rutc, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 360, 119, -1));
        getContentPane().add(rutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 398, 119, -1));

        tablaarri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaarri);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 500, 200));

        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                try{
            PreparedStatement pst = cn.prepareStatement("INSERT INTO arriendo(cod_arri,num_serie,costo_total,fec_arri,fec_dev_est,fec_entr_real,dias_retra,multa,costo_arri,rutC,rutT) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
            
            pst.setInt(1,(Integer.parseInt(codarri.getText())));
            pst.setInt(2,(Integer.parseInt(numserie.getText())));
            pst.setInt(3,(Integer.parseInt(total.getText())));
            pst.setString(4, fecarri.getText()); 
            pst.setString(5, fecdev.getText()); 
            pst.setString(6, fecent.getText()); 
            pst.setInt(7,(Integer.parseInt(diar.getText())));
            pst.setInt(8,(Integer.parseInt(multa.getText())));
            pst.setInt(9,(Integer.parseInt(cosarri.getText())));
            pst.setInt(10,(Integer.parseInt(rutc.getText())));
            pst.setInt(11,(Integer.parseInt(rutt.getText())));
           
           
            pst.executeUpdate();
         
        JOptionPane.showMessageDialog(null,"El arriendo fue agregado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        listaarri();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codarri;
    private javax.swing.JTextField cosarri;
    private javax.swing.JTextField diar;
    private javax.swing.JTextField fecarri;
    private javax.swing.JTextField fecdev;
    private javax.swing.JTextField fecent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField multa;
    private javax.swing.JTextField numserie;
    private javax.swing.JTextField rutc;
    private javax.swing.JTextField rutt;
    private javax.swing.JTable tablaarri;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
Conectar cone=new Conectar();
Connection cn=cone.con;
}
